<a href="https://colab.research.google.com/github/MR-just01/Basics-of-Python/blob/main/Intropandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

##Series
index = ['a','b' , 'c' , 'd' ,'e']
data = [1,2,3,4,5]
series = pd.Series(data , index = index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
#dataframe

df = pd.DataFrame([[12,34,5,5,] ,[78,23,23,12] , [3,4,5,3]] , columns=['c0','c1','c2','c3'],index= ['ro' , 'r1' ,'r2'])
print(df)

    c0  c1  c2  c3
ro  12  34   5   5
r1  78  23  23  12
r2   3   4   5   3

In [12]:
data = pd.read_csv('data.csv')
# data.head()
#we can pass the int value in the arguement  of head so we can print the table as long as we want
data.head(8)

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3

In [13]:
print("this is the last five rows and columns ")
data.tail()
# bottom rows
# similary for the tail also
data.tail(10)

this is the last five rows and columns

     Duration  Pulse  Maxpulse  Calories
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [19]:
data.sample()

    Duration  Pulse  Maxpulse  Calories
88        45    129       103     242.0

In [18]:
#feather file and  parquet file

data.sample(10)

     Duration  Pulse  Maxpulse  Calories
98         30    109       131     188.2
165        60    110       145     300.0
150        60    106       134     343.0
42         60    100       122     329.4
104        30     92       108      92.7
6          60    110       136     374.0
1          60    117       145     479.0
65        180     90       130     800.4
76         45    105       134     251.0
25         60    100       120     250.0

In [23]:
data.sample(10 , random_state=2)

     Duration  Pulse  Maxpulse  Calories
42         60    100       122     329.4
23         45    105       132     246.0
45         60     99       119     273.0
48         45    108       129     298.0
13         60    104       132     379.3
3          45    109       175     282.4
6          60    110       136     374.0
150        60    106       134     343.0
66        150    105       135     873.4
64         20    110       130     131.4

In [25]:
data.columns.tolist()

['Duration', 'Pulse', 'Maxpulse', 'Calories']

In [26]:
data.index

RangeIndex(start=0, stop=169, step=1)

In [28]:
data.shape

(169, 4)

In [29]:
data.size

676

In [30]:
data.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [36]:
data.loc[0 , 'Pulse']

np.int64(110)

In [43]:
data.loc[0:10 , ["Pulse", "Calories"] ]

    Pulse  Calories
0     110     409.1
1     117     479.0
2     103     340.0
3     109     282.4
4     117     406.0
5     102     300.0
6     110     374.0
7     104     253.3
8     109     195.1
9      98     269.0
10    103     329.3

In [47]:
data.loc[[0,4,10 ],["Pulse" , "Calories"] ]

    Pulse  Calories
0     110     409.1
4     117     406.0
10    103     329.3